[package]
authors = []
edition = "2018"
name = "quantum_tunnel"
version = "0.1.0"
[dependencies]
futures = "0.3.5"
futures_codec = "0.4.1"
gumdrop = "0.7"
simple-error = "0.1.9"
sp-core = "2.0.0-rc.4"
sp-finality-grandpa = "2.0.0-rc.4"
sp-runtime = "2.0.0-rc.4"
thiserror = "1"
toml = "0.5.6"
url = "1.7.2"
log = "0.4.8"
serde_json = "*"
hyper = "0.13"
bytes = "*"
bip39 = "0.6.0-beta.1"
tiny-hderive = "0.2.1"

[dependencies.signatory-secp256k1]
version = "0.20.0"
path = "../signatory/signatory-secp256k1"
default_features = false

[dependencies.signatory]
version = "0.20.0"
path = "../signatory"
default_features = false
features = ["ecdsa"]

[dependencies.abscissa_core]
version = "0.5.2"

[dependencies.tokio-tungstenite]
version = "0.10.1"

[dependencies.serde]
features = ["serde_derive"]
version = "1"

[dependencies.tendermint]
default-features = false
path = "../tendermint-rs/tendermint"
version = "0.14.0"

[dependencies.tendermint-rpc]
default-features = false
features = ["client"]
path = "../tendermint-rs/rpc"
version = "0.14.0"

[dependencies.tendermint_light_client]
default-features = false
path = "../tendermint_light_client"
version = "0.2.3"

[dependencies.tokio]
default_features = false
features = ["rt-core"]
version = "0.2"

[dev-dependencies]
once_cell = "1.2"

[dev-dependencies.abscissa_core]
features = ["testing"]
version = "0.5.2"
