[package]
authors = []
edition = "2018"
name = "quantum_tunnel"
version = "0.1.0"
[dependencies]
futures = "0.3.5"
futures_codec = "0.4.1"
gumdrop = "0.7"
simple-error = "0.1.9"
sp-core = "2.0.0-rc.4"
sp-finality-grandpa = "2.0.0-rc.4"
sp-runtime = "2.0.0-rc.4"
thiserror = "1"
toml = "0.5.6"
url = "1.7.2"
log = "0.4.8"
serde_json = "*"
hyper = "0.13"
bytes = "*"
tiny-bip39 = "0.7.3"
tiny-hderive = "0.2.1"
crossbeam-channel = "0.4.2"
subtle-encoding = { version = "0.5.1", features = ["bech32-preview"] }
hex = "0.4.2"
rand = "0.6.5"
parse_duration = "*"
regex = "1"
cast = "0.1.0"
signature = "*"

[dependencies.signatory-secp256k1]
version = "0.20.1"
git = "https://github.com/ChorusOne/signatory"
tag = "v0.20.1"
default_features = false

[dependencies.signatory]
version = "0.20.0"
git = "https://github.com/ChorusOne/signatory"
tag = "v0.20.1"
default_features = false
features = ["ecdsa"]

[dependencies.abscissa_core]
version = "0.5.2"

[dependencies.tokio-tungstenite]
version = "0.10.1"

[dependencies.serde]
features = ["serde_derive"]
version = "1"

[dependencies.tendermint]
default-features = false
git = "https://github.com/ChorusOne/tendermint-rs.git"
branch = "master"
version = "0.14.0"

[dependencies.tendermint-rpc]
default-features = false
features = ["client"]
git = "https://github.com/ChorusOne/tendermint-rs.git"
branch = "master"
version = "0.14.0"

[dependencies.tendermint_light_client]
default-features = false
git = "https://github.com/ChorusOne/tendermint_light_client.git"
branch = "client"
version = "0.2.5"

[dependencies.tokio]
default_features = false
features = ["rt-core"]
version = "0.2"

[dev-dependencies]
once_cell = "1.2"

[dev-dependencies.abscissa_core]
features = ["testing"]
version = "0.5.2"
