[package]
name = "quantum_tunnel"
authors = []
version = "0.1.0"
edition = "2018"

[dependencies]
gumdrop = "0.7"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
toml = "0.5.6"
futures = "0.3.5"
sp-runtime = "2.0.0-rc.3"
sp-finality-grandpa = "2.0.0-rc.3"
url = "2.1"
simple-error = "0.1.9"

[dependencies.abscissa_core]
version = "0.5.2"
# optional: use `gimli` to capture backtraces
# see https://github.com/rust-lang/backtrace-rs/issues/189
# features = ["gimli-backtrace"]

[dependencies.tendermint_light_client]
default-features = false
#git = "https://github.com/ChorusOne/tendermint_light_client.git"
#branch = "client"
version = "0.2.3"
path = "../tendermint_light_client"

[dependencies.tendermint-rpc]
default-features = false
path = "../tendermint-rs/rpc"
version = "0.14.0"
features = ["client"]

[dependencies.tendermint]
default-features = false
path = "../tendermint-rs/tendermint"
version = "0.14.0"

[dependencies.tokio]
default_features = false
features = ["rt-core"]
version = "0.2"

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
once_cell = "1.2"
